<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tabela extends \Application\Entity\Tabela implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = ['arrCampos' => NULL, 'arrTabelaChaveOrigem' => NULL, 'arrTabelaChaveDestino' => NULL];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->arrCampos, $this->arrTabelaChaveOrigem, $this->arrTabelaChaveDestino);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'ds_nome', 'sn_temporario', 'sn_excluido', 'ds_descricao', 'ds_tag', 'arrCampos', 'arrTabelaChaveOrigem', 'arrTabelaChaveDestino', '' . "\0" . 'Application\\Entity\\Tabela' . "\0" . 'objSistema'];
        }

        return ['__isInitialized__', 'id', 'ds_nome', 'sn_temporario', 'sn_excluido', 'ds_descricao', 'ds_tag', '' . "\0" . 'Application\\Entity\\Tabela' . "\0" . 'objSistema'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tabela $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->arrCampos, $this->arrTabelaChaveOrigem, $this->arrTabelaChaveDestino);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjSistema()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjSistema', []);

        return parent::getObjSistema();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjSistema($objSistema)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjSistema', [$objSistema]);

        return parent::setObjSistema($objSistema);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsNome', []);

        return parent::getDsNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsNome($ds_nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsNome', [$ds_nome]);

        return parent::setDsNome($ds_nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getSnTemporario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSnTemporario', []);

        return parent::getSnTemporario();
    }

    /**
     * {@inheritDoc}
     */
    public function setSnTemporario($sn_temporario = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSnTemporario', [$sn_temporario]);

        return parent::setSnTemporario($sn_temporario);
    }

    /**
     * {@inheritDoc}
     */
    public function getSnExcluido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSnExcluido', []);

        return parent::getSnExcluido();
    }

    /**
     * {@inheritDoc}
     */
    public function setSnExcluido($sn_excluido = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSnExcluido', [$sn_excluido]);

        return parent::setSnExcluido($sn_excluido);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrCampos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrCampos', []);

        return parent::getArrCampos();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsDescricao', []);

        return parent::getDsDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsDescricao($ds_descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsDescricao', [$ds_descricao]);

        return parent::setDsDescricao($ds_descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsTag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsTag', []);

        return parent::getDsTag();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsTag($ds_tag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsTag', [$ds_tag]);

        return parent::setDsTag($ds_tag);
    }

    /**
     * {@inheritDoc}
     */
    public function addCampo($objCampo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCampo', [$objCampo]);

        return parent::addCampo($objCampo);
    }

    /**
     * {@inheritDoc}
     */
    public function addTabelaChaveOrigem($objTabelaChave)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTabelaChaveOrigem', [$objTabelaChave]);

        return parent::addTabelaChaveOrigem($objTabelaChave);
    }

    /**
     * {@inheritDoc}
     */
    public function addTabelaChaveDestino($objTabelaChave)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTabelaChaveDestino', [$objTabelaChave]);

        return parent::addTabelaChaveDestino($objTabelaChave);
    }

}
