<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Campo extends \Application\Entity\Campo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'ds_nome', 'ds_prop', 'sn_pk', 'ds_descricao', 'nr_ordem', '' . "\0" . 'Application\\Entity\\Campo' . "\0" . 'objTabela', 'arrTabelaChaveCampoOrigem', 'arrTabelaChaveCampoDestino'];
        }

        return ['__isInitialized__', 'id', 'ds_nome', 'ds_prop', 'sn_pk', 'ds_descricao', 'nr_ordem', '' . "\0" . 'Application\\Entity\\Campo' . "\0" . 'objTabela', 'arrTabelaChaveCampoOrigem', 'arrTabelaChaveCampoDestino'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Campo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjTabela()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjTabela', []);

        return parent::getObjTabela();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjTabela($objTabela)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjTabela', [$objTabela]);

        return parent::setObjTabela($objTabela);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsNome', []);

        return parent::getDsNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsNome($ds_nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsNome', [$ds_nome]);

        return parent::setDsNome($ds_nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsProp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsProp', []);

        return parent::getDsProp();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsProp($ds_prop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsProp', [$ds_prop]);

        return parent::setDsProp($ds_prop);
    }

    /**
     * {@inheritDoc}
     */
    public function getSnPk()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSnPk', []);

        return parent::getSnPk();
    }

    /**
     * {@inheritDoc}
     */
    public function setSnPk($sn_pk = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSnPk', [$sn_pk]);

        return parent::setSnPk($sn_pk);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsDescricao', []);

        return parent::getDsDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsDescricao($ds_descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsDescricao', [$ds_descricao]);

        return parent::setDsDescricao($ds_descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getNrOrdem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNrOrdem', []);

        return parent::getNrOrdem();
    }

    /**
     * {@inheritDoc}
     */
    public function setNrOrdem($nr_ordem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNrOrdem', [$nr_ordem]);

        return parent::setNrOrdem($nr_ordem);
    }

    /**
     * {@inheritDoc}
     */
    public function addTabelaChaveOrigem($objTabelaChave)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTabelaChaveOrigem', [$objTabelaChave]);

        return parent::addTabelaChaveOrigem($objTabelaChave);
    }

    /**
     * {@inheritDoc}
     */
    public function addTabelaChaveDestino($objTabelaChave)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTabelaChaveDestino', [$objTabelaChave]);

        return parent::addTabelaChaveDestino($objTabelaChave);
    }

}
