<div class="row">

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Tabelas</h3>
            </div>
            <div class="panel-body">

                <table class="table">
                    <thead>
                    <tr>
                        <th>Nome</th>
                    </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <th scope="row">Tabela</th>
                        <tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>


</div>
