<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('The Mode Project')
            ->setSeparator(' - ')
            ->setAutoEscape(false);
        ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet("/css/bootstrap.min.css")
            ->prependStylesheet("https://use.fontawesome.com/releases/v5.0.8/css/all.css");
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->appendFile("/js/libs/jquery-3.1.0.min.js")
            ->appendFile("/js/libs/bootstrap.min.js")
            // ->appendFile("https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js")
            // ->appendFile("https://cdn.jsdelivr.net/npm/vue")

            ->appendFile("https://vuejs.org/js/vue.js")
            ->appendFile($this->basePath("js/libs/lodash.js"))
            ->appendFile("https://unpkg.com/axios/dist/axios.min.js")
            ->appendFile("http://cdn.jsdelivr.net/npm/sortablejs@1.7.0/Sortable.min.js")
            ->appendFile("https://cdn.rawgit.com/David-Desmaisons/Vue.Draggable/master/dist/vuedraggable.min.js")
            ->appendFile("https://unpkg.com/vue-select@2.4.0/dist/vue-select.js")
        ?>
    </head>

    <body>
        <?php echo $this->partial('layout/barra_topo'); ?>

        <div class="container-fluid">
            <div class="row">
                <?php echo $this->partial('layout/menu'); ?>
                <?= $this->content ?>
            </div>
        </div>
        <?// = $this->inlineScript() ?>
    </body>
</html>