<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('The Mode Project')
            ->setSeparator(' - ')
            ->setAutoEscape(false);
        ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet("/css/bootstrap.min.css")
            ->prependStylesheet($this->basePath("js/libs/css/animate.css"))
            ->prependStylesheet("https://use.fontawesome.com/releases/v5.7.2/css/all.css");
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->appendFile($this->basePath("/js/libs/jquery-3.1.0.min.js"))
            ->appendFile($this->basePath("/js/libs/bootstrap.min.js"))
            ->appendFile($this->basePath("js/libs/vue.js"))
            ->appendFile($this->basePath("js/libs/lodash.js"))
            ->appendFile($this->basePath("js/libs/axios.min.js"))
            ->appendFile($this->basePath("js/libs/Sortable.min.js"))
            ->appendFile($this->basePath("js/libs/vuedraggable.umd.js"))
            ->appendFile($this->basePath("js/libs/vue-select.js"));
        ?>
    </head>

    <body>
        <?php echo $this->partial('layout/barra_topo'); ?>

        <div class="container-fluid">
            <div class="row">
                <?php echo $this->partial('layout/menu'); ?>
                <?= $this->content ?>
            </div>
        </div>
        <?// = $this->inlineScript() ?>
    </body>
</html>