<div class="row">

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Tabelas</h3>
            </div>

            <div class="panel-body" id="vueApp-lista-tabela">

                <div class="form-group">
                    <input type="text" class="form-control" id="ds_busca" placeholder="Buscar">
                </div>

                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Tabela</th>
                        <th>Descrição</th>
                        <th>Ligações</th>
                    </tr>
                    </thead>

                    <tbody>
                        <tr v-for="arrValores in arrTabelas">
                            <th scope="row">{{arrValores.id}}</th>
                            <td>{{arrValores.ds_nome}}</td>
                        <tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Discover Modules</h3>
            </div>
            <div class="panel-body">

                <table class="table">
                    <thead>
                    <tr>
                        <th>Descrição</th>
                    </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <th scope="row">Descricao</th>
                        <tr>
                    </tbody>
                </table>

                <table class="table">
                    <thead>
                    <tr>
                        <th>Descrição</th>
                    </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <th scope="row">Descricao</th>
                        <tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>



<script>
var app_lista_tabela = new Vue({
    el: '#vueApp-lista-tabela',
    data: {
        arrTabelas: [],
        sn_carregando : true
    },

    created : function() {
        fetch('http://localhost:8080/tabela/lista-tabelas')
            .then(response => response.json())
            .then(
                json => {
                    this.arrTabelas = json;
                    this.sn_carregando = false;
                }
            )
    }
});
    </script>
