<div class="row" id="vueApp-lista-tabela">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Tabelas</h3>
            </div>

            <div class="panel-body">

                <div class="form-group">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-10">
                                <input type="text"
                                       class="form-control"
                                       id="ds_busca"
                                       placeholder="Buscar"
                                       v-model="ds_filtro" />
                            </div>

                            <div class="col-sm-2">
                                <button type="button" class="btn btn-secondary"
                                    id="btn_add_tabela"
                                    v-on:click="modalIncluir"
                                    data-toggle="modal" data-target="#modalFormulario">Nova</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="container">
                    <div class="row">
                        <table class="table" id="table_lista_tabela">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Tabela</th>
                                <th>Descrição</th>
                                <th>Ligações</th>
                                <th></th>
                            </tr>
                            </thead>

                            <tbody>
                            <tr v-for="arrValores in arrTabelas">
                                <th scope="row">{{arrValores.id}}</th>
                                <td>{{arrValores.ds_nome}}</td>
                                <td></td>
                                <td></td>
                                <td>
                                    <button type="button" class="btn btn-secondary"
                                            v-on:click="modalEditar(arrValores.id)"
                                            style="font-size: 10px;"
                                            class="btn btn-primary" data-toggle="modal" data-target="#modalFormulario">
                                        <i class="fas fa-edit"></i>
                                    </button>

                                    <button type="button" class="btn btn-secondary"
                                            v-on:click="verDetalhes(arrValores.id)"
                                            style="font-size: 10px;"
                                            class="btn btn-primary" >
                                        <i class="fas fa-edit"></i>
                                    </button>

                                    <button type="button" class="btn btn-secondary"
                                            v-on:click="modalExcluir(arrValores.id)"
                                            style="font-size: 10px;"
                                            class="btn btn-primary" data-toggle="modal" data-target="#modalExcluir">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>



    <!-- Form -->
    <div class="modal" tabindex="-1" role="dialog" id="modalFormulario">
        <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div class="modal-content" >
                <div class="modal-header">
                    <h5 class="modal-title">Tabela</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">

                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="tab-nova"
                               data-toggle="tab" href="#nova" role="tab" aria-controls="nova"
                               v-on:click="tabAtiva('nova')"
                               aria-selected="true">Nova</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="tab-sql" data-toggle="tab"
                               href="#sql" role="tab" aria-controls="sql"
                               v-on:click="tabAtiva('sql')"
                               aria-selected="false">SQL</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="nova"
                             role="tabpanel" aria-labelledby="tab-nova">
                            <div class="form-group">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="row">
                                                <label for="ds_tabela">Nome da Tabela</label>
                                                <input type="text" class="form-control"
                                                       id="ds_tabela"
                                                       v-model="ds_tabela"
                                                       placeholder="Nome da Tabela">
                                            </div>
                                            <div class="row">
                                                <label for="ds_sql">Descrição</label>
                                                <textarea class="form-control"
                                                          id="ds_descricao"
                                                          v-model="ds_descricao"
                                                          cols="50"
                                                          rows="10"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="sql" role="tabpanel" aria-labelledby="tab-sql">
                            <div class="form-group">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <label for="ds_sql">SQL</label>
                                            <textarea class="form-control"
                                                id="exampleFormControlTextarea1"
                                                v-model="ds_sql"
                                                cols="50"
                                                rows="10"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary"
                            v-on:click="submitModalIncluir"
                            data-dismiss="modal"
                            id="btn_salvar_tabela">Save changes</button>
                    <button type="button" class="btn btn-secondary"
                            data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>


    <!-- modal excluir -->
    <div class="modal" tabindex="-1" role="dialog" id="modalExcluir">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Excluir</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    Deseja realmente excluir o registro?
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary"
                            v-on:click="doDelete()"
                            data-dismiss="modal">Sim</button>
                    <button type="button" class="btn btn-secondary"
                            data-dismiss="modal">Não</button>
                </div>
            </div>
        </div>
    </div>

    <!-- modal temporario -->
    <div class="modal" tabindex="-1" role="dialog" id="modalTemporario">
        <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Comparar tabelas</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    A tabela atual está na esquerda, e a nova na direita.

                    <div class="row" id="">
                        <div class="col-md-6">
                            {{ arrComparacao.ds_nome }}
                        </div>
                        <div class="col-md-6">
                            {{ arrComparacao.ds_nome_temp }}
                        </div>
                    </div>


                    <div class="row" id="" v-for="(arrCampo, nr_key) in arrCamposIguais">
                        <div class="col-md-6">
                            <table>
                                <tr>
                                    <td>
                                        Nome do Campo
                                    </td>
                                    <td>
                                        Tipo do Campo
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <input type="checkbox" value="1" v-model="arrCampo.arrCampo1.sn_selecionado"> -
                                        {{ arrCampo.arrCampo1.ds_nome }}
                                    </td>
                                    <td>
                                        {{ arrCampo.arrCampo1.ds_prop }}
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table>
                                <tr>
                                    <td>
                                        Nome do Campo
                                    </td>
                                    <td>
                                        Tipo do Campo
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <input type="checkbox" value="1" v-model="arrCampo.arrCampo2.sn_selecionado"> -
                                        {{ arrCampo.arrCampo2.ds_nome }}
                                    </td>
                                    <td>
                                        {{ arrCampo.arrCampo2.ds_prop }}
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>

                    <div class="row" id="" v-for="(arrCampo, index) in arrSemIgualdadeA">
                        <div class="col-md-6">
                            <table>
                                <tr>
                                    <td>
                                        <input type="checkbox" value="1" v-model="arrCampo.sn_selecionado"
                                               checked="checked"> -
                                        {{ arrCampo.ds_nome }}
                                    </td>
                                    <td>
                                        {{ arrCampo.ds_prop }}
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table>
                                <tr>
                                    <td>
                                        -
                                    </td>
                                    <td>
                                        -
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>

                    <div class="row" id="" v-for="(arrCampo, index) in arrSemIgualdadeB">
                        <div class="col-md-6">
                            <table>
                                <tr>
                                    <td>
                                        -
                                    </td>
                                    <td>
                                        -
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table>
                                <tr>
                                    <td>
                                        <input type="checkbox" value="1" v-model="arrCampo.sn_selecionado"
                                               checked="checked">
                                        {{ arrCampo.ds_nome }}
                                    </td>
                                    <td>
                                        {{ arrCampo.ds_prop }}
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary"
                            v-on:click="doMergeTabela()">Merge</button>
                </div>
            </div>
        </div>
    </div>

</div>




<script>

    var app_lista_tabela = new Vue({
        el: '#vueApp-lista-tabela',

        data: {
            arrTabelas: [],
            arrTabelasOriginal: [],
            sn_carregando : true,
            ds_filtro : '',

            // form
            ds_tabela : '',
            ds_descricao : '',
            nr_tabela_id : 0,
            ds_sql : '',
            arrCampos : [],

            // tabs
            ds_tab_ativa : 'nova',

            // comparador
            arrComparacao: [],
            arrCamposIguais: [],
            arrSemIgualdadeA: [],
            arrSemIgualdadeB: [],

            // ultimo campo excluido
            arrCampoExcluido : [],
            sn_desfazer_campo_excluido : false


        },

        created: function() {
            this.getListRegistros();
        },

        watch: {
            ds_filtro: function ()
            {
                var ds_filtrar = this.ds_filtro;
                this.arrTabelas = this.arrTabelasOriginal;

                if (_.isEmpty(ds_filtrar)) {
                    return;
                }

                this.arrTabelas = _.filter(
                    this.arrTabelasOriginal,
                    function (arrValor) {
                        return arrValor.ds_nome
                            .toLowerCase()
                            .indexOf(ds_filtrar.toLowerCase()) >= 0;
                    }
                );

            }
        },

        methods: {
            getListRegistros: function() {
                fetch(
                    '/tabela/lista-tabelas',
                    {
                        credentials: 'include'
                    }
                )
                .then(objResponse => objResponse.json())
                .then(
                    arrJson => {
                        this.arrTabelas = arrJson;
                        this.arrTabelasOriginal = arrJson;
                        this.sn_carregando = false;

                        this.iniciarCorrecaoTemporarios();
                    }
                );
            },

            getRegistroEditar: function(nr_tabela_id) {
                fetch(
                    '/tabela/get/' + nr_tabela_id,
                    {
                        credentials: 'include'
                    }
                )
                .then(objResponse => objResponse.json())
                .then(
                    arrJson => {
                        var arrTabela = arrJson.arrTabela[0];
                        var arrCampos = arrJson.arrCampos;

                        this.nr_tabela_id = arrTabela.id;
                        this.ds_tabela = arrTabela.ds_nome;
                        this.ds_descricao = arrTabela.ds_descricao;
                        this.arrCampos = arrCampos;
                    }
                );
            },

            modalIncluir: function () {
                this.limparCampos();
            },

            modalEditar: function (nr_tabela_id) {
                this.nr_tabela_id = nr_tabela_id;
                this.getRegistroEditar(nr_tabela_id);
            },

            modalExcluir: function(nr_tabela_id) {
                this.nr_tabela_id = nr_tabela_id;
            },

            submitModalIncluir: function() {
                if (this.ds_tab_ativa == 'nova') {
                    this.ds_sql = '';
                }

                if (this.ds_tab_ativa == 'sql') {
                    this.ds_tabela = '';
                }

                var arrPost = {
                    nr_tabela_id : this.nr_tabela_id,
                    ds_tabela : this.ds_tabela,
                    ds_descricao: this.ds_descricao,
                    ds_sql : this.ds_sql
                };

                axios.post(
                    '/tabela/update',
                    arrPost,
                    {
                        credentials: 'include',
                        withCredentials: true
                    }
                )
                .then(
                    function (objResponse) {
                        if (objResponse.data.sn_sucesso == true) {
                            app_lista_tabela.getListRegistros();
                            app_lista_tabela.limparCampos();

                            // processar temporarios?
                            var sn_temporario = objResponse.data.sn_tem_temporario;

                            if (sn_temporario == true) {
                                app_lista_tabela.iniciarCorrecaoTemporarios();
                            }
                            return;
                        }
                    }
                )
                .catch(
                    function (error) {
                        console.log(error);
                    }
                );
            },

            doDelete: function() {
                fetch(
                    '/tabela/delete/' + this.nr_tabela_id,
                    {
                        credentials: 'include'
                    }
                )
                .then(objResponse => objResponse.json())
                .then(
                    arrJson => {
                        this.getListRegistros();
                        return;
                    }
                );
            },

            tabAtiva: function(ds_tab) {
                this.ds_tab_ativa = ds_tab;
            },

            // busca registros temporarios para serem corrigidos
            iniciarCorrecaoTemporarios: function() {
                fetch(
                    '/tabela/lista-tabelas-temporarias',
                    {
                        credentials: 'include'
                    }
                )
                .then(objResponse => objResponse.json())
                .then(
                    arrJson => {
                        this.arrComparacao = arrJson.arrComparacao;
                        this.arrCamposIguais = arrJson.arrCamposIguais;
                        this.arrSemIgualdadeA = arrJson.arrSemIgualdadeA;
                        this.arrSemIgualdadeB = arrJson.arrSemIgualdadeB;

                        // abrir modal de comparacao
                        // adrw $("#modalTemporario").modal();
                    }
                );
            },

            limparCampos: function() {
                this.nr_tabela_id = 0;
                this.ds_tabela = '';
                this.ds_descricao = '';
                this.ds_sql = '';
                this.arrCampos = [];
            },

            verDetalhes: function(tabela_id) {
                document.location = '/tabela/detalhes/' + tabela_id;
            },


            doMergeTabela: function() {
                var arrPost = {
                    arrComparacao : this.arrComparacao,
                    arrCamposIguais : this.arrCamposIguais,
                    arrSemIgualdadeA : this.arrSemIgualdadeA,
                    arrSemIgualdadeB: this.arrSemIgualdadeB
                };

                axios.post(
                    '/tabela/merge',
                    arrPost,
                    {
                        credentials: 'include'
                    }
                )
                .then(
                    function (objResponse) {
                        if (objResponse.data.sn_sucesso == true) {
                            app_lista_tabela.getListRegistros();
                            app_lista_tabela.limparCampos();

                            // processar temporarios?
                            var sn_temporario = objResponse.data.sn_tem_temporario;

                            if (sn_temporario == true) {
                                app_lista_tabela.iniciarCorrecaoTemporarios();
                            }
                            return;
                        }
                    }
                )
                .catch(
                    function (error) {
                        console.log(error);
                    }
                );
            }
        }
    });
</script>