<div class="row" id="vueApp-lista-tabela">

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Tabelas</h3>
            </div>

            <div class="panel-body">

                <div class="form-group">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-10">
                                <input type="text"
                                    class="form-control"
                                    id="ds_busca"
                                    placeholder="Buscar"
                                    v-model="ds_filtro" />
                            </div>

                            <div class="col-sm-2">
                                <button type="button" class="btn btn-secondary"
                                    v-on:click="modalIncluir"
                                    class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Nova</button>
                            </div>
                        </div>
                    </div>
                </div>

                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Tabela</th>
                        <th>Descrição</th>
                        <th>Ligações</th>
                    </tr>
                    </thead>

                    <tbody>
                        <tr v-for="arrValores in arrTabelas">
                            <th scope="row">{{arrValores.id}}</th>
                            <td>{{arrValores.ds_nome}}</td>
                        <tr>
                    </tbody>
                </table>


            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Discover Modules</h3>
            </div>
            <div class="panel-body">

                <table class="table">
                    <thead>
                    <tr>
                        <th>Descrição</th>
                    </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <th scope="row">Descricao</th>
                        <tr>
                    </tbody>
                </table>

                <table class="table">
                    <thead>
                    <tr>
                        <th>Descrição</th>
                    </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <th scope="row">Descricao</th>
                        <tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>



    <div class="modal" tabindex="-1" role="dialog" id="exampleModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Tabela</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <div class="form-group">
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-10">
                                    <label for="ds_tabela">Nome da Tabela</label>
                                    <input type="text" class="form-control"
                                        id="ds_tabela"
                                        v-model="ds_tabela"
                                        placeholder="Nome da Tabela">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary"
                        v-on:click="submitModalIncluir">Save changes</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

</div>




<script>

var app_lista_tabela = new Vue({
    el: '#vueApp-lista-tabela',

    data: {
        arrTabelas: [],
        arrTabelasOriginal: [],
        sn_carregando : true,
        ds_filtro : '',

        // form
        ds_tabela : ''
    },

    created: function() {
        fetch('http://localhost:8080/tabela/lista-tabelas')
            .then(response => response.json())
            .then(
                json => {
                    this.arrTabelas = json;
                    this.arrTabelasOriginal = json;
                    this.sn_carregando = false;
                }
            )
    },

    watch: {
        ds_filtro: function ()
        {
            var ds_filtrar = this.ds_filtro;
            this.arrTabelas = this.arrTabelasOriginal;

            if (_.isEmpty(ds_filtrar)) {
                return;
            }

            this.arrTabelas = _.filter(
                this.arrTabelasOriginal,
                function (arrValor) {
                    return arrValor.ds_nome
                        .toLowerCase()
                        .indexOf(ds_filtrar.toLowerCase()) >= 0;
                }
            );

        }
    },

    methods: {
        modalIncluir: function () {
            console.log('aqui');
            // do nothing
        },

        submitModalIncluir: function() {
            var arrPost = {
                ds_tabela : this.ds_tabela
            };

            axios.post(
                '/tabela/update',
                arrPost
            )
            .then(
                function (response) {
                    console.log(response);
                }
            )
            .catch(
                function (error) {
                    console.log(error);
                }
            );
        }
    }
});
</script>