<div id="vueApp-sql">
    <div class="">
        <div class="row" style="margin-left: 1300px">
        &nbsp;
        </div>
    </div>
    <div class="">
        <div class="row">
            <div id="div_resultado">
            </div>
        </div>
    </div>
</div>

<?php
$this->headLink()
    ->prependStylesheet(
        'https://unpkg.com/tabulator-tables@4.2.7/dist/css/tabulator.min.css'
    );

echo $this->inlineScript()
    ->appendFile(
        'https://unpkg.com/tabulator-tables@4.2.7/dist/js/tabulator.min.js'
    )
    ->appendFile(
        $this->basePath('js/sql/popup-executado.js')
    );
?>