<main role="main" class="col-md-12 ml-sm-auto col-lg-12 px-4" id="">
    <div class="container-fluid">
        <div class="row" >

            <div id="vueApp-sql">
                <div class="">
                    <div class="row">

                        <div id="div_resultado">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<?php
$this->headLink()
    ->prependStylesheet(
        'https://unpkg.com/tabulator-tables@4.2.7/dist/css/tabulator.min.css'
    );

echo $this->inlineScript()
    ->appendFile(
        'https://unpkg.com/tabulator-tables@4.2.7/dist/js/tabulator.min.js'
    )
    ->appendFile(
        $this->basePath('js/sql/popup-executado.js')
    );
?>