<style type="text/css" media="screen">
#editor {
    margin: 0;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    width: 950px;
    height: 300px;
    margin-left: 20px;
}
</style>

<div id="">
    <div class="row" id="vueApp-conexao">
        <div class="col-sm-6">
            <div class="form-group" style="margin: 5px">
                <label for="lista_conexoes">Conexões</label>
                <select class="form-control"
                    id="lista_conexoes"
                    v-model="conexao_atual"
                    @change="getConexaoDatabases()">
                    <option name="">
                        Selecione
                    </option>
                    <option v-for="arrValor in arrConexao" v-bind:value="arrValor">
                        {{arrValor.ds_nome}}
                    </option>
                </select>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="form-group" style="margin: 5px">
                <label for="lista_database">Database</label>
                <select class="form-control" id="lista_database" v-model="database_atual">
                    <option name="">
                        Selecione
                    </option>
                    <option v-for="arrDatabaseValor in arrDatabase" v-bind:value="arrDatabaseValor">
                        {{arrDatabaseValor.Database}}
                    </option>
                </select>
            </div>
        </div>
    </div>

    <div class="row">
        <div id="editor">SELECT * FROM nu_grupos_pessoas limit 10
        </div>
    </div>
</div>

<div id="vueApp-sql">
    <div class="row">
        <div class="btn-group" role="group" aria-label="Basic example" style="margin-left: 20px; margin-top: 5px;">
            <button type="button" class="btn btn-secondary"
                @click="getInfoFromTabelaSelecionada()"><i class="fas fa-table"></i></button>
            <button type="button" class="btn btn-secondary">Middle</button>
            <button type="button" class="btn btn-secondary">Right</button>
        </div>
    </div>

    <div class="">
        <div class="row" style="margin-left: 1100px">
        &nbsp;
        </div>
    </div>

    <div class="">
        <div class="row">
            <div class="overflow-auto" style="height: 300px; width: 650px; margin-left: 20px;">
                <table class="table table-sm table-dark" v-for="arrTabela in arrTabelaInfo">
                    <thead>
                        <tr>
                            <th scope="col">Nome</th>
                            <th scope="col">Descricao</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">{{arrTabela.ds_nome}}</th>
                            <td>{{arrTabela.ds_descricao}}</td>
                        </tr>

                        <tr v-for="arrCampo in arrTabela.arrCampos">
                            <th scope="row">{{arrCampo.ds_nome}}</th>
                            <td>{{arrCampo.ds_descricao}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="overflow-auto" style="height: 300px; width: 650px; margin-left: 20px;">
                <table class="table table-sm table-dark" v-for="arrTabela in arrTabelaInfo">
                    <thead>
                        <tr>
                            <th scope="col">Nome</th>
                            <th scope="col">Descricao</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="arrTabelaChave in arrTabela.arrTabelaChavesOrigem">
                            <td scope="row">
                                <a href="#" @click="setAndCopyInnerJoin(arrTabelaChave)">
                                    {{arrTabelaChave.ds_nome_campo_origem}}
                                    >
                                    {{arrTabelaChave.ds_nome_tabela_destino}}
                                    .
                                    {{arrTabelaChave.ds_nome_campo_destino}}
                                </a>
                            </td>
                            <td>{{arrTabelaChave.ds_descricao}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>



        </div>
    </div>
</div>

<?php
echo $this->inlineScript()
    ->appendFile(
        $this->basePath('js/libs/ace/src-noconflict/ace.js')
    )
    ->appendFile(
        $this->basePath('js/libs/ace/src-noconflict/ext-language_tools.js')
    )
    ->appendFile(
        $this->basePath('js/sql/sql.js')
    );
?>