<style type="text/css" media="screen">
#editor {
    margin: 0;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    width: 750px;
    height: 300px;
}
</style>

<div id="">
    <pre id="editor">
SELECT
    *
FROM
    pessoas
    </pre>
</div>

<div id="vueApp-sql">
    <div class="container">
        <div class="row" style="margin-left: 1300px">
        &nbsp;
        </div>
    </div>
    <div class="container">
        <div class="row">

            <table class="table table-sm table-dark" v-for="arrValores in arrTabelaInfo">
                <thead>
                    <tr>
                        <th scope="col">Nome</th>
                        <th scope="col">Descricao</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">{{arrValores.ds_nome}}</th>
                        <td>{{arrValores.ds_descricao}}</td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
</div>

<?php
echo $this->inlineScript()
    ->appendFile(
        $this->basePath('js/libs/ace/src-noconflict/ace.js')
    )
    ->appendFile(
        $this->basePath('js/libs/ace/src-noconflict/ext-language_tools.js')
    )
    ->appendFile(
        $this->basePath('js/sql/sql.js')
    );
?>